# project informations for Bukkit in order to register our plugin with all it components
# ${-} are variables from Maven (pom.xml) which will be replaced after the build
name: ${project.parent.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}

# meta informations for plugin managers
authors: [games647, 'https://github.com/games647/FastLogin/graphs/contributors']
description: |
    ${project.description}
website: ${project.url}
dev-url: ${project.url}

# Without Protocollib the plugin does not work at all
depend: [ProtocolLib]

softdepend:
    - ProtocolSupport
    # Auth plugins
    - xAuth
    - AuthMe
    - CrazyLogin
    - LoginSecurity

commands:
    ${project.parent.name}:
        description: 'Label the invoker or the player specified as premium'
        aliases: [prem, premium, loginfast]
        usage: /<command> [player]
        permission: ${project.artifactId}.command.premium

permissions:
    ${project.parent.name}.command.premium:
        description: 'Label themselves as premium using a command'
        default: true