# project informations for Bukkit in order to register our plugin with all it components
# ${-} are variables from Maven (pom.xml) which will be replaced after the build
name: ${project.parent.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}

# meta informations for plugin managers
authors: [games647, 'https://github.com/games647/FastLogin/graphs/contributors']
description: |
    ${project.description}
website: ${project.url}
dev-url: ${project.url}

# Load the plugin as early as possible to inject it for all players
load: STARTUP

softdepend:
    # We require either ProtocolLib or ProtocolSupport
    - ProtocolSupport
    - ProtocolLib
    # Auth plugins - we delay the hook
#    - xAuth
#    - AuthMe
#    - LogIt
#    - CrazyLogin
#    - LoginSecurity
#    - RoyalAuth
#    - UltraAuth

commands:
    ${project.parent.name}:
        description: 'Label the invoker as premium'
        aliases: [prem, premium, loginfast]
        usage: /<command> [player]
        permission: ${project.artifactId}.command.premium

    cracked:
        description: 'Label the invoker or the player specified as cracked if he was marked premium before'
        aliases: [unpremium]
        usage: /<command> [player]
        permission: ${project.artifactId}.command.cracked

    import-auth:
        description: 'Imports the auth data from another auto login'
        usage: /<command> [player]
        permission: ${project.artifactId}.command.import

permissions:
    ${project.artifactId}.command.premium:
        description: 'Label themselves as premium'
        default: true

    ${project.artifactId}.command.premium.other:
        description: 'Label others as premium'
        children:
            ${project.artifactId}.command.premium: true

    ${project.artifactId}.command.cracked:
        description: 'Label themselves as cracked'
        default: true

    ${project.artifactId}.command.cracked.other:
        description: 'Label others as cracked'
        children:
            ${project.artifactId}.command.cracked: true