# project informations for Bukkit in order to register our plugin with all it components
# ${-} are variables from Maven (pom.xml) which will be replaced after the build
name: ${project.parent.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}

# meta informations for plugin managers
authors: [games647, 'https://github.com/games647/FastLogin/graphs/contributors']
description: |
    ${project.description}
website: ${project.url}
dev-url: ${project.url}

# Without Protocollib the plugin does not work at all
depend: [ProtocolLib]

softdepend:
    - ProtocolSupport
    # Auth plugins
    - xAuth
    - AuthMe
    - CrazyLogin
    - LoginSecurity
    - RoyalAuth
    - UltraAuth

commands:
    ${project.parent.name}:
        description: 'Label the invoker as premium'
        aliases: [prem, premium, loginfast]
        usage: /<command> [player]
        permission: ${project.artifactId}.command.premium

    unpremium:
        description: 'Label the invoker or the player specified as cracked if he was marked premium before'
        aliases: [cracked]
        usage: /<command> [player]
        permission: ${project.artifactId}.command.unpremium

permissions:
    ${project.artifactId}.command.premium:
        description: 'Label themselves as premium'
        default: true

    ${project.artifactId}.command.premium.other:
        description: 'Label others as premium'
        children:
            ${project.artifactId}.command.premium: true

    ${project.artifactId}.command.unpremium:
        description: 'Label themselves as cracked'
        default: true

    ${project.artifactId}.command..unpremium.other:
        description: 'Label others as cracked'
        children:
            ${project.artifactId}.command.unpremium: true